### ISSUE TITLE
Upload relative to basepath

### ISSUE THREAD

**Issue by timkpaine** [youngthejames/jupyterlab_filetree#10]
- [ ] `export` basepath [here](https://github.com/youngthejames/jupyterlab_filetree/blob/master/src/index.ts#L38)
- [ ] use basepath [here](https://github.com/youngthejames/jupyterlab_filetree/blob/master/src/index.ts#L360)
- [ ] import basepath [here](https://github.com/youngthejames/jupyterlab_filetree/blob/master/src/upload.ts#L17)
- [ ] use basepath [here](https://github.com/youngthejames/jupyterlab_filetree/blob/master/src/upload.ts#L178)

**Comment by youngthejames** [comment]
implemented in [PR14](https://github.com/youngthejames/jupyterlab_filetree/pull/14)
