### ISSUE TITLE
JupyterLab 2.0 support?

### ISSUE THREAD

**Issue by snakers4** [youngthejames/jupyterlab_filetree#16]
```
ValueError: The extension "jupyterlab_filetree" does not yet support the current version of JupyterLab.
```
probably same issue as here
https://github.com/aquirdTurtle/Collapsible_Headings/issues/19

**Comment by youngthejames** [comment]
Are you using the latest version of the repo? I commited changes for 2.0 a few weeks ago.

**Comment by snakers4** [comment]
Just used `jupyter labextension install jupyterlab_filetree`
Maybe the version in the repo is older?

**Comment by youngthejames** [comment]
I think that command pulls the latest tagged release from npm and not the latest repo code. I'll publish a release for jlab 2.0 support later today.

**Comment by youngthejames** [comment]
I published v.0.2.2 which includes the commits for jlab 2.0.0 support.
