### ISSUE TITLE
folder name which starts with another folder name prevents opening  

### ISSUE THREAD

**Issue by remziduzagac** [youngthejames/jupyterlab_filetree#18]
Hi,

Lets assume that we have two folders on same level and name of second folder starts with first ones name such as;
/query/
/query_corrected/
plugin fails to open first one

thanks

**Comment by remziduzagac** [comment]
It is working fine with jupyter 2.1 the previous test was on 1.2.7

**Comment by youngthejames** [comment]
There was a previous release with this bug that I had previously patched. So upgrading to the newest release for jlab 2.x.x likely picked up the change.
