### ISSUE TITLE
Sub directories and files don't show in file tree view; Also cannot click into directories.

### ISSUE THREAD

**Issue by TheVinhLuong102** [youngthejames/jupyterlab_filetree#21]
I'm using this JupyterLab FileTree extension in JupyterLab 2.1.5 in Python 3.8.3.

In the File Tree view, I can only see the top-level directories and files, and no subdirs and sub files.

Furthermore, when I try clicking on a directory, I cannot enter it. Instead, I seem to be prompted to edit the directory name instead (screenshot attached).

Your help to review this issue would be most appreciated. Thank you.

<img width="742" alt="Screenshot 2020-07-09 00 07 01" src="https://user-images.githubusercontent.com/7796578/87008127-23423800-c178-11ea-8256-0ad342ba364f.png">

**Comment by youngthejames** [comment]
I upgraded to the latest JLab build (2.1.5) and reinstalled the extension and it seems to be working. Double clicking the file name opens the title editing feature. Clicking the folder icon on the side should open up the subdirectory if it is occupied. Does clicking the icon not work for you? 

I know its not great UX. I'm planning a cleanup / overhaul when I have some free time.

**Comment by TheVinhLuong102** [comment]
@youngthejames oh I see, I didn't know that the folder icons are  the means for expanding/collapsing the tree view :) I'm so used to the arrow ">" icons for expanding/collapsing. Ok I've got it working now. Thank you @youngthejames!
