### ISSUE TITLE
viewing hidden files

### ISSUE THREAD

**Issue by SultanOrazbayev** [youngthejames/jupyterlab_filetree#22]
This might too specific of a use, but it would be great if there was an easy way to toggle viewing hidden files (e.g. .gitignore). Not sure if this is possible, but would be great if it's something that literally can be toggled on or off during a session.

**Comment by SultanOrazbayev** [comment]
Just in case, here's a discussion for a similar request on the main jupyterlab: https://github.com/jupyterlab/jupyterlab/issues/2049

**Comment by sar** [comment]
+1 would be great to see it handled extension side as the paths are within addressable space by jupyterlab

Here's what an optional toggle might look like in extension settings:
```json
{
    "showHiddenFiles": true
}
```

**Comment by youngthejames** [comment]
Currently the contents manager provided by jupyterlab does not return hidden file paths. 
So unfortunately there is nothing that can be done at this time.
