### ISSUE TITLE
filetree does not dislpay and triggers exception

### ISSUE THREAD

**Issue by joequant** [youngthejames/jupyterlab_filetree#23]
I'm getting errors when I try to run filetree.  Nothing is displaying in the filetree

When I look at the console messages I get an error when it tries to look at the type for this code in filetree.js

        if (object.type === "directory") {
            icon = ui_components_1.LabIcon.resolveElement({ icon: this.dr.getFileType("directory").icon });
            icon.className = "jp-DirListing-itemIcon";
            tr.className += " filetree-folder";
        }

Object seems to be undefined which triggers and exception which causes the tree not to display.

**Comment by joequant** [comment]
Here is the stack trace.

Uncaught (in promise) TypeError: can't access property "type", e is undefined
    createTreeElement filetree.js:192
    buildTableContents filetree.js:107
    buildTable filetree.js:53
    iu filetree.js:34
    createTreeElement filetree.js:192
    buildTableContents filetree.js:123
    buildTable filetree.js:67
    h filetree.js:48
    promise callback*h filetree.js:44
    p filetree.js:286
    s validate.js:95
    promise index.js:156
    promise callback*2dC9/s</e.prototype.activatePlugin index.js:155
    i index.js:275
    start index.js:274
    o index.out.js:1227
    ANye index.out.js:1273
    Webpack 6

**Comment by joequant** [comment]
Somehow when sortContents is called, there is an extra element that gets added.

**Comment by joequant** [comment]
This is the inputs and output of sortContents.  Somehow it's adding another element

e: (1) […]
0: {…}
content: null
created: "2020-09-06T18:20:56.538435Z"
format: null
last_modified: "2020-09-06T18:20:56.538435Z"
mimetype: "text/x-python"
name: "test.py"
path: "test.py"
size: 16
type: "file"
writable: true
<prototype>: {…}
length: 1
<prototype>: []
​
i: (2) […]
0: (2) […]
0: ""
1: NaN
length: 2
<prototype>: []
1: (2) […]
0: "test.py"
1: 0
length: 2
<prototype>: []
length: 2
<prototype>: []

**Comment by joequant** [comment]
I think the for...in loop is picking up inherited members and should ba a for..of loop

**Comment by joequant** [comment]
Put in fixes with #24 and #26

**Comment by youngthejames** [comment]
merged
