### ISSUE TITLE
"Timestamp" field not updating when a file is updated

### ISSUE THREAD

**Issue by jgunstone** [youngthejames/jupyterlab_filetree#28]
this is a great extension!

see the issue shown in the screenshot where the Timestamp of a file isn't updating when the file is updated:

![image](https://user-images.githubusercontent.com/21370980/98808579-4590de80-2414-11eb-9e7b-f7003034b30c.png)

**Comment by youngthejames** [comment]
The time stamps on files are read at the time the file tree is generated. I know it's not ideal, but my hacky fix is thru the refresh button on the top which will refresh the entire tree and meta data.
