### ISSUE TITLE
Extension does not work

### ISSUE THREAD

**Issue by luiul** [youngthejames/jupyterlab_filetree#29]
The extension is not working for me.  jupyter-widgest/jupyterlab-manager and jupyterlab/toc do work in the JupyterLab. I'm working in an environment with the following requirements: 
```
jupyter==1.0.0
lxml==4.5.1
MarkupSafe==1.1.1
matplotlib==3.3.2
notebook==6.0.3
numpy==1.18.1
openpyxl==3.0.4
pandas==1.1.2
Pillow==7.2.0
scikit-learn==0.23.2
scipy==1.4.1
seaborn==0.11.0
SQLAlchemy==1.3.18
xlrd==1.2.0
``` 

My Jupyter: 
```
jupyter core     : 4.7.0
jupyter-notebook : 6.1.5
qtconsole        : 5.0.1
ipython          : 7.19.0
ipykernel        : 5.4.2
jupyter client   : 6.1.7
jupyter lab      : 2.2.6
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 5.0.5
```

Node v12.19.0.

**Comment by youngthejames** [comment]
Not much to go on without an error message, but I would guess this is due to the current version of the extension is for compatibility with jlab 2.0 release. You can try using one of the older tagged versions and see if those work.
