### ISSUE TITLE
filetree makes Pandas dataframe columns display as uppercase

### ISSUE THREAD

**Issue by jpweytjens** [youngthejames/jupyterlab_filetree#6]
#### Description
Enabling the jupyterlab_filetree extensions incorrectly displays the column names of a pandas DataFrame as uppercase.

#### Screenshots
With the filetree extension loaded.

![filetree](https://user-images.githubusercontent.com/34494702/56219908-d6041300-6067-11e9-85e2-ba55c130d5d4.PNG)

Without the filetree extension.

![no_filetree](https://user-images.githubusercontent.com/34494702/56219909-d6041300-6067-11e9-8fac-c798a291cb9e.PNG)

#### Potential cause
I assume it has something to do with the `uppercase` tags in [index.css](https://github.com/youngthejames/jupyterlab_filetree/blob/master/style/index.css). Though I don't know how these interefere with `pandas`.

**Comment by youngthejames** [comment]
Are you using the latest code? I believe I saw and fixed this issue a while ago and doesn't seem to occur in my local build.
<img width="493" alt="Screen Shot 2019-04-16 at 3 53 25 PM" src="https://user-images.githubusercontent.com/7410224/56239767-dac4c900-605f-11e9-98b1-7bece6d31556.png">

**Comment by jpweytjens** [comment]
I'm using the following extensions

```
jupyter labextension list
JupyterLab v0.35.4
Known labextensions:
   app dir: /home/johannes/.cache/pypoetry/virtualenvs/project-py3.7/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
        @ryantam626/jupyterlab_code_formatter v0.2.0  enabled  OK
        jupyterlab_filetree v0.1.0  enabled  OK
```

Is there a more recent version than v0.1.0 publicly available?

**Comment by jpweytjens** [comment]
The issues is closed, but I'm using the latest version of the labextension installed according to the instructions provided. Could you please explain why you have closed the issue, as the problem hasn't been addressed?

**Comment by youngthejames** [comment]
I have not been able to reproduce the issue and I have verified that it has
been resolved by another user, but I can help you resolve. Which
instructions are you referring to? Did you install via npm or did you clone
the repository directly from GitHub?

It would also help if you could inspect the header element with the browser
developer tools to see where the capitalization is being picked up.

**Comment by jpweytjens** [comment]
I ran 

```
jupyter labextension install jupyterlab_filetree
```

which gives me version `0.1.0` as shown above. I use Jupyterlab `0.35.5` and Google Chrome `74.0.3729.131`.

I have little experience with browser developer tools. But I did find these.

```
th {
  border-bottom: var(--jp-border-width) solid var(--jp-border-color2);
  font-size: var(--jp-ui-font-size0);
  font-weight: 600;
  letter-spacing: 1px;
  margin: 0px;
  padding: 8px 12px;
  text-transform: uppercase;
}

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>file</th>
      <th>vdab_referentienummer</th>
      <th>vdab_id_nummer</th>
    </tr>
  </thead>
  <tbody>
   ...
  </tbody>
</table>
```

The entire html file can be found [here](https://github.com/youngthejames/jupyterlab_filetree/files/3141803/JupyterLab.txt).
